development:
  adapter: postgresql
  encoding: utf8
  database: ${DATABASE_NAME}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  host: ${DATABASE_HOST}
  timeout: 5000
  prepared_statements: false
