common: &common
  adapter: postgresql
  host: ${DATABASE_URL}
  database: ${DATABASE_NAME}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  encoding: utf8
  timeout: 5000
  prepared_statements: false

development:
  <<: *common
  database: canvas
  open: true

test:
  <<: *common
  database: canvas_test_rails3_<%= ENV['TEST_ENV_NUMBER'] %>
  shard1: canvas_test_rails3_shard1
  shard2: canvas_test_rails3_shard2
  test_shard_1: canvas_test_rails3_shard1
  test_shard_2: canvas_test_rails3_shard2
