common: &default_settings
  # For heroku Review Apps, the HEROKU_APP_NAME holds the app DOMAIN.
  # That should take precendence if both variables exist.
  domain: <%= ENV.fetch('HEROKU_APP_NAME', ENV['DOMAIN']) %>
  ssl: true

development:
  <<: *default_settings
  ssl: false

test:
  <<: *default_settings
  domain: localhost
  ssl: false

staging:
  <<: *default_settings

production:
  <<: *default_settings

