common: &default_settings
  logger: rails
  
  # Log Level seems like the only setting here we would want to change without a code release.
  log_level: <%= ENV['LOG_LEVEL'] %> 

development:
  <<: *default_settings
  log_context: false

test:
  <<: *default_settings

staging:
  <<: *default_settings

production:
  <<: *default_settings
  # TODO: just testing if this makes the logs work in Heroku. If so, figure out
  # how to deal with dev vs production logs using ENV vars.
  logger: syslog
  app_ident: canvas-lms
  facilities:
    - user
# Another option we could setup.
#  logger: syslog
#  app_ident: canvas-lms
#  daemon_ident: canvas-lms-daemon
#  include_pid: false
#  facilities:
#  - user
#  - local3
